#if !defined(PINS_H)
#define PINS_H

#define ULTRASONIC_TRIGGER_RIGHT PB12
#define ULTRASONIC_LEFT PB13
#define ULTRASONIC_RIGHT PB14
#define HALL_SENSOR PB15
#define BRIDGE_SERVO PA_8
#define FACE_SERVO PA_9
#define ULTRASONIC_TRIGGER_LEFT PA10
#define IR_SELECT PA11
#define IR_RESET PA12
#define LEFT_EDGE PA15
#define RIGHT_EDGE PB3
#define LEFT_ENCODER_2 PB_4
#define RIGHT_ENCODER_1 PB5
#define MOTOR_RIGHT_F PB_6
#define MOTOR_RIGHT_B PB_7
#define MOTOR_LEFT_F PB_8
#define MOTOR_LEFT_B PB_9
#define I2C_SDA PB11
#define I2C_SCL PB10
#define LEFT_ARM PB_1
#define LEFT_CLAW PB_0
#define RIGHT_ARM PA_7
#define RIGHT_CLAW PA_6
#define IR_READ PA5
#define LINE_FOLLOW_LEFT PA4
#define LINE_FOLLOW_RIGHT PA3
#define SPARE_PIN_2 PA2
#define JOYSTICK_LR PA1
#define JOYSTICK_UD PA0
#define JOYSTICK_CLICK PC15
#define LEFT_ENCODER_1 PC14
#define RIGHT_ENCODER_2 PC_13

#endif // PINS_H
